apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  labels:
    app: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: messaging
          image: fevtutorcr.azurecr.io/messaging
          imagePullPolicy: Always
          ports:
            - containerPort: 3001